[build]
  command = "cd frontend && npm install && npm run build"
  publish = "frontend/dist"

[build.environment]
  NODE_VERSION = "16"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200